use iced::Size;

pub const MAIN_WINDOW_WIDTH: f32 = 1024.0;
pub const MAIN_WINDOW_HEIGHT: f32 = 768.0;

pub const WINDOW_SIZE: Size<f32> = Size::new(MAIN_WINDOW_WIDTH, MAIN_WINDOW_HEIGHT);

pub const MEDIUM_WINDOW_SIZE: Size<f32> =
    Size::new(MAIN_WINDOW_WIDTH / 1.5, MAIN_WINDOW_HEIGHT / 1.5);

pub const SMALL_WINDOW_SIZE: Size<f32> =
    Size::new(MAIN_WINDOW_WIDTH / 2.0, MAIN_WINDOW_HEIGHT / 2.0);

pub const DIALOG_WINDOW_SIZE: Size<f32> =
    Size::new(MAIN_WINDOW_WIDTH / 3.0, MAIN_WINDOW_HEIGHT / 5.0);

pub const SCROLLBAR_WIDTH: f32 = 8.0;

pub const ACTION_BAR_HEIGHT: f32 = 100.0;

pub const CALENDER_MONTH_YEAR_HEIGHT: f32 = 34.0;
pub const CALENDER_DAY_OF_WEEK_HEIGHT: f32 = 18.0;
pub const CALENDER_DAY_WIDTH: f32 = 34.0;
pub const CALENDER_DAY_HEIGHT: f32 = 24.0;
pub const TOTAL_CALENDER_WIDTH: f32 = CALENDER_DAY_WIDTH * 7.0;
pub const TOTAL_CALENDER_HEIGHT: f32 =
    CALENDER_MONTH_YEAR_HEIGHT + CALENDER_DAY_OF_WEEK_HEIGHT + CALENDER_DAY_WIDTH * 6.0;

pub const LOGBOX_HEIGHT: f32 = 20.0;

pub const DASHBOARD_WIDTH: f32 = TOTAL_CALENDER_WIDTH;
pub const DASHBOARD_TAB_CONTENT_HEIGHT: f32 =
    MAIN_WINDOW_HEIGHT - ACTION_BAR_HEIGHT - TOTAL_CALENDER_HEIGHT - LOGBOX_HEIGHT;

pub const EDITOR_WIDTH: f32 = MAIN_WINDOW_WIDTH - DASHBOARD_WIDTH;

pub const CONTEXT_MENU_MIN_WIDTH: f32 = 130.0;
pub const CONTEXT_MENU_TEXT_PADDING: f32 = 25.0;
pub const CONTEXT_MENU_BORDER_WIDTH: f32 = 1.0;
pub const CONTEXT_MENU_HEIGHT: f32 = 28.0;
pub const CONTEXT_MENU_RADIOCHECK_WIDTH: f32 = 25.0;
