use iced::Size;

pub const MAIN_WINDOW_WIDTH: f32 = 1024.0;
pub const MAIN_WINDOW_HEIGHT: f32 = 768.0;

pub const WINDOW_SIZE: Size<f32> = Size::new(MAIN_WINDOW_WIDTH, MAIN_WINDOW_HEIGHT);

pub const MEDIUM_WINDOW_SIZE: Size<f32> =
    Size::new(MAIN_WINDOW_WIDTH / 1.5, MAIN_WINDOW_HEIGHT / 1.5);

pub const SMALL_WINDOW_SIZE: Size<f32> =
    Size::new(MAIN_WINDOW_WIDTH / 2.0, MAIN_WINDOW_HEIGHT / 2.0);

pub const DIALOG_WINDOW_SIZE: Size<f32> =
    Size::new(MAIN_WINDOW_WIDTH / 3.0, MAIN_WINDOW_HEIGHT / 5.0);

pub const CALENDER_DAY_WIDTH: f32 = 34.0;
pub const TOTAL_CALENDER_WIDTH: f32 = CALENDER_DAY_WIDTH * 7.0;

pub const DASHBOARD_WIDTH: f32 = TOTAL_CALENDER_WIDTH;
pub const EDITOR_WIDTH: f32 = MAIN_WINDOW_WIDTH - DASHBOARD_WIDTH;
