use iced::{
    Element,
    widget::{self, Space, Text, column, row},
};
use serde::{Deserialize, Deserializer, Serialize, Serializer};

use crate::content::{ContentAction, UpgradedContent};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
/// The types of tasks that can be created
pub enum TaskType {
    Standard,
    MultiBinary,
}

#[derive(Debug, Clone, PartialEq)]
/// Types of messages generated by Standard tasks
pub enum StandardMessage {
    ToggledCheckbox,
    TextEdit(ContentAction),
}

#[derive(Debug, Default)]
/// The standard task with a text box and a single checkbox
pub struct StandardTask {
    completed: bool,
    text: UpgradedContent,
}

#[derive(Debug, Default, Serialize, Deserialize)]
/// StandardTask as stored on disk
struct StandardTaskDisk {
    completed: bool,
    text: String,
}

impl StandardTask {
    /// Update task state based on the message
    pub fn update(&mut self, message: StandardMessage) {
        match message {
            StandardMessage::ToggledCheckbox => {
                self.completed = !self.completed;
            }
            StandardMessage::TextEdit(content_action) => {
                self.text.perform(content_action);
            }
        }
    }

    /// Returns the completion status of the task element
    pub fn is_completed(&self) -> bool {
        self.completed
    }

    /// The expanded ui that drops down for the standard task
    pub fn expanded_ui<'a>(&'a self) -> Element<'a, StandardMessage> {
        let text = widget::text_editor(self.text.raw_content())
            .on_action(move |action| StandardMessage::TextEdit(ContentAction::Standard(action)));

        text.into()
    }
}

impl From<&StandardTask> for StandardTaskDisk {
    fn from(non_disk: &StandardTask) -> Self {
        StandardTaskDisk {
            completed: non_disk.completed,
            text: non_disk.text.text(),
        }
    }
}

impl From<&StandardTaskDisk> for StandardTask {
    fn from(disk: &StandardTaskDisk) -> Self {
        StandardTask {
            completed: disk.completed,
            text: UpgradedContent::with_text(&disk.text),
        }
    }
}

impl Serialize for StandardTask {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let disk = StandardTaskDisk::from(self);
        disk.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for StandardTask {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let disk_element = StandardTaskDisk::deserialize(deserializer)?;

        let standard_element = StandardTask::from(&disk_element);

        Ok(standard_element)
    }
}

#[derive(Debug, Clone, PartialEq)]
/// Types of messages generated by MultiBinary tasks
pub enum MultiBinaryMessage {
    ToggledNth(usize),
    ToggledOverride,
    TextEdit(ContentAction),
}

#[derive(Debug, Default)]
/// A task with any number of subtask components
pub struct MultiBinaryTaskElement {
    subtask_completion: Vec<bool>,
    completion_override: bool,
    text: UpgradedContent,
}

#[derive(Debug, Default, Serialize, Deserialize)]
/// The MultiBinaryTask as stored on disk
struct MultiBinaryTaskDisk {
    subtask_completion: Vec<bool>,
    completion_override: bool,
    text: String,
}

impl MultiBinaryTaskElement {
    /// Update task state based on the message
    pub fn update(&mut self, message: MultiBinaryMessage) {
        match message {
            MultiBinaryMessage::ToggledNth(index) => {
                self.subtask_completion[index] = !self.subtask_completion[index];
            }
            MultiBinaryMessage::ToggledOverride => {
                match (self.is_completed(), self.completion_override) {
                    (false, _) => self.completion_override = true,
                    (true, false) => {}
                    (true, true) => self.completion_override = !self.completion_override,
                }
            }
            MultiBinaryMessage::TextEdit(content_action) => {
                self.text.perform(content_action);
            }
        }
    }

    /// Creates a new element with the given number of subtasks
    pub fn with_empty_subtasks(subtask_count: usize) -> Self {
        Self {
            subtask_completion: vec![false; subtask_count],
            completion_override: false,
            text: UpgradedContent::default(),
        }
    }

    pub fn subtask_completion(&self) -> &Vec<bool> {
        &self.subtask_completion
    }

    /// Returns if the task as a whole is completed. If all subtasks are complete this returns true. If the completion
    /// has been manually overriden, this will return true, even if not all subtasks have been completed
    pub fn is_completed(&self) -> bool {
        if self.completion_override {
            return true;
        }

        self.subtask_completion
            .iter()
            .all(|&subtask_completed| subtask_completed)
    }

    /// Performs the action on the underlying UpgradedContent
    pub fn content_perform(&mut self, content_action: ContentAction) {
        self.text.perform(content_action);
    }
}

impl From<&MultiBinaryTaskElement> for MultiBinaryTaskDisk {
    fn from(non_disk: &MultiBinaryTaskElement) -> Self {
        MultiBinaryTaskDisk {
            subtask_completion: non_disk.subtask_completion.clone(),
            completion_override: non_disk.completion_override,
            text: non_disk.text.text(),
        }
    }
}

impl From<&MultiBinaryTaskDisk> for MultiBinaryTaskElement {
    fn from(disk: &MultiBinaryTaskDisk) -> Self {
        MultiBinaryTaskElement {
            subtask_completion: disk.subtask_completion.clone(),
            completion_override: disk.completion_override,
            text: UpgradedContent::with_text(&disk.text),
        }
    }
}

impl Serialize for MultiBinaryTaskElement {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let disk = MultiBinaryTaskDisk::from(self);
        disk.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for MultiBinaryTaskElement {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let disk_element = MultiBinaryTaskDisk::deserialize(deserializer)?;

        let non_disk_element = MultiBinaryTaskElement::from(&disk_element);

        Ok(non_disk_element)
    }
}

#[derive(Debug, Serialize, Deserialize)]
/// A complete multi binary task
pub struct MultiBinaryTask {
    pub(crate) element: MultiBinaryTaskElement,
    pub(crate) subtasks: Vec<String>,
}

impl MultiBinaryTask {
    /// The expanded ui that drops down for the multi binary task
    pub fn expanded_ui<'a>(
        element: &'a MultiBinaryTaskElement,
        subtasks: &Vec<String>,
    ) -> Element<'a, MultiBinaryMessage> {
        let mut subtask_checkboxes = column![];

        for (i, completion) in element.subtask_completion().iter().enumerate() {
            let checkbox = widget::checkbox(*completion)
                .on_toggle(move |_ticked| MultiBinaryMessage::ToggledNth(i));

            let name_text = Text::new(subtasks[i].clone());

            subtask_checkboxes = subtask_checkboxes.push(row![
                Space::new().width(15),
                checkbox,
                Space::new().width(5),
                name_text
            ]);
        }

        let text = widget::text_editor(element.text.raw_content())
            .on_action(move |action| MultiBinaryMessage::TextEdit(ContentAction::Standard(action)));

        column![subtask_checkboxes, text].into()
    }
}

#[derive(Debug, Serialize, Deserialize)]
/// A task of the given type
pub enum TaskData {
    Standard(StandardTask),
    MultiBinary(MultiBinaryTask),
}
