use iced::widget::text_editor::Content;
use serde::{Deserialize, Deserializer, Serialize, Serializer};

use crate::content::{ContentAction, UpgradedContent};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
/// The types of tasks that can be created
pub enum TaskType {
    Standard,
    MultiBinary,
}

#[derive(Debug, Clone, PartialEq)]
/// Types of messages generated by Standard tasks
pub enum StandardMessage {
    CheckedBox(bool),
    TextEdit(ContentAction),
}

#[derive(Debug, Default)]
/// The standard task with a text box and a single checkbox
pub struct StandardTask {
    completed: bool,
    text: UpgradedContent,
}

#[derive(Debug, Default, Serialize, Deserialize)]
/// StandardTask as stored on disk
struct StandardTaskDisk {
    completed: bool,
    text: String,
}

impl StandardTask {
    /// Set if the task is completed or not
    pub fn set_completion(&mut self, completed: bool) {
        self.completed = completed;
    }

    /// Returns the completion status of the task element
    pub fn is_completed(&self) -> bool {
        self.completed
    }

    /// Performs the action on the underlying UpgradedContent
    pub fn content_perform(&mut self, content_action: ContentAction) {
        self.text.perform(content_action);
    }

    /// Returns the raw text content
    pub fn raw_content(&self) -> &Content {
        self.text.raw_content()
    }
}

impl From<&StandardTask> for StandardTaskDisk {
    fn from(non_disk: &StandardTask) -> Self {
        StandardTaskDisk {
            completed: non_disk.completed,
            text: non_disk.text.text(),
        }
    }
}

impl From<&StandardTaskDisk> for StandardTask {
    fn from(disk: &StandardTaskDisk) -> Self {
        StandardTask {
            completed: disk.completed,
            text: UpgradedContent::with_text(&disk.text),
        }
    }
}

impl Serialize for StandardTask {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let disk = StandardTaskDisk::from(self);
        disk.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for StandardTask {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let disk_element = StandardTaskDisk::deserialize(deserializer)?;

        let standard_element = StandardTask::from(&disk_element);

        Ok(standard_element)
    }
}

#[derive(Debug, Clone, PartialEq)]
/// Types of messages generated by MultiBinary tasks
pub enum MultiBinaryMessage {
    CheckedNth((usize, bool)),
    CheckedOverride(bool),
    TextEdit(ContentAction),
}

#[derive(Debug, Default)]
/// A task with any number of subtask components
pub struct MultiBinaryTask {
    subtask_completion: Vec<bool>,
    completion_override: bool,
    text: UpgradedContent,
}

#[derive(Debug, Default, Serialize, Deserialize)]
/// The MultiBinaryTask as stored on disk
struct MultiBinaryTaskDisk {
    subtask_completion: Vec<bool>,
    completion_override: bool,
    text: String,
}

impl MultiBinaryTask {
    /// Creates a new element with the given number of subtasks
    pub fn with_empty_subtasks(subtask_count: usize) -> Self {
        Self {
            subtask_completion: vec![false; subtask_count],
            completion_override: false,
            text: UpgradedContent::default(),
        }
    }

    /// Set the completion status of the subtask at the given index
    pub fn set_subtask_completion(&mut self, completion_index: usize, completed: bool) {
        self.subtask_completion[completion_index] = completed;
    }

    pub fn subtask_completion(&self) -> &Vec<bool> {
        &self.subtask_completion
    }

    pub fn set_completion_override(&mut self, completion_override: bool) {
        self.completion_override = completion_override;
    }

    /// Returns if the task as a whole is completed. If all subtasks are complete this returns true. If the completion
    /// has been manually overriden, this will return true, even if not all subtasks have been completed
    pub fn is_completed(&self) -> bool {
        if self.completion_override {
            return true;
        }

        self.subtask_completion
            .iter()
            .all(|&subtask_completed| subtask_completed)
    }

    /// Performs the action on the underlying UpgradedContent
    pub fn content_perform(&mut self, content_action: ContentAction) {
        self.text.perform(content_action);
    }

    /// Returns the raw text content
    pub fn raw_content(&self) -> &Content {
        self.text.raw_content()
    }
}

impl From<&MultiBinaryTask> for MultiBinaryTaskDisk {
    fn from(non_disk: &MultiBinaryTask) -> Self {
        MultiBinaryTaskDisk {
            subtask_completion: non_disk.subtask_completion.clone(),
            completion_override: non_disk.completion_override,
            text: non_disk.text.text(),
        }
    }
}

impl From<&MultiBinaryTaskDisk> for MultiBinaryTask {
    fn from(disk: &MultiBinaryTaskDisk) -> Self {
        MultiBinaryTask {
            subtask_completion: disk.subtask_completion.clone(),
            completion_override: disk.completion_override,
            text: UpgradedContent::with_text(&disk.text),
        }
    }
}

impl Serialize for MultiBinaryTask {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let disk = MultiBinaryTaskDisk::from(self);
        disk.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for MultiBinaryTask {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let disk_element = MultiBinaryTaskDisk::deserialize(deserializer)?;

        let non_disk_element = MultiBinaryTask::from(&disk_element);

        Ok(non_disk_element)
    }
}
