use super::TaskId;
use crate::{
    month_day::MonthDay,
    upgraded_content::{ContentAction, UpgradedContent},
    user_preferences::preferences,
};

use chrono::{Datelike, NaiveDate, Weekday};
use iced::{
    Element,
    Length::Fill,
    widget::{self, Space, Text, button, checkbox, column, row},
};
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::{collections::BTreeMap, fs};
use strum::Display;

#[derive(Debug, Clone, PartialEq)]
/// types of messages generated by Standard template tasks
pub enum StandardMessage {
    CheckedBox(bool),
    TextEdit(ContentAction),
}

#[derive(Debug, Default)]
/// The standard task with a text box and a single checkbox
pub struct StandardTaskElement {
    completed: bool,
    text: UpgradedContent,
}

#[derive(Debug, Default, Serialize, Deserialize)]
/// StandardTaskElement as stored on disk
struct StandardTaskElementDisk {
    completed: bool,
    text: String,
}

impl From<&StandardTaskElement> for StandardTaskElementDisk {
    fn from(non_disk: &StandardTaskElement) -> Self {
        StandardTaskElementDisk {
            completed: non_disk.completed,
            text: non_disk.text.text(),
        }
    }
}

impl From<&StandardTaskElementDisk> for StandardTaskElement {
    fn from(disk: &StandardTaskElementDisk) -> Self {
        StandardTaskElement {
            completed: disk.completed,
            text: UpgradedContent::with_text(&disk.text),
        }
    }
}

impl Serialize for StandardTaskElement {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let disk = StandardTaskElementDisk::from(self);
        disk.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for StandardTaskElement {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let disk_element = StandardTaskElementDisk::deserialize(deserializer)?;

        let standard_element = StandardTaskElement::from(&disk_element);

        Ok(standard_element)
    }
}

impl StandardTaskElement {
    /// set if the task was completed or not
    pub fn set_completion(&mut self, completed: bool) {
        self.completed = completed;
    }

    /// Performs the action on the underlying UpgradedContent
    pub fn text_perform(&mut self, content_action: ContentAction) {
        self.text.perform(content_action);
    }
}

#[derive(Debug, Default, Serialize, Deserialize)]
/// Contains all the individual element entries in a standard task
pub struct StandardTask {
    elements: BTreeMap<NaiveDate, StandardTaskElement>,
}

impl StandardTask {
    /// Adds an empty element with the given date to the task elements if it does not exist
    pub fn add_empty_element(&mut self, active_date: NaiveDate) {
        self.elements.entry(active_date).or_default();
    }

    /// Returns mutable access to a element at the given date, if it exists
    pub fn get_element_mut(&mut self, active_date: NaiveDate) -> Option<&mut StandardTaskElement> {
        self.elements.get_mut(&active_date)
    }
}

#[derive(Debug, Clone, PartialEq)]
/// messages generated by MultiBinary tasks
pub enum MultiBinaryMessage {
    CheckedNth((usize, bool)),
    CheckedOverride(bool),
    TextEdit(ContentAction),
}

#[derive(Debug, Default)]
/// A task with any number of subtask components
pub struct MultiBinaryTaskElement {
    subtask_completion: Vec<bool>,
    completion_override: bool,
    text: UpgradedContent,
}

#[derive(Debug, Default, Serialize, Deserialize)]
/// The MultiBinaryTaskElement as stored on disk
struct MultiBinaryTaskElementDisk {
    subtask_completion: Vec<bool>,
    completion_override: bool,
    text: String,
}

impl From<&MultiBinaryTaskElement> for MultiBinaryTaskElementDisk {
    fn from(non_disk: &MultiBinaryTaskElement) -> Self {
        MultiBinaryTaskElementDisk {
            subtask_completion: non_disk.subtask_completion.clone(),
            completion_override: non_disk.completion_override,
            text: non_disk.text.text(),
        }
    }
}

impl From<&MultiBinaryTaskElementDisk> for MultiBinaryTaskElement {
    fn from(disk: &MultiBinaryTaskElementDisk) -> Self {
        MultiBinaryTaskElement {
            subtask_completion: disk.subtask_completion.clone(),
            completion_override: disk.completion_override,
            text: UpgradedContent::with_text(&disk.text),
        }
    }
}

impl Serialize for MultiBinaryTaskElement {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let disk = MultiBinaryTaskElementDisk::from(self);
        disk.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for MultiBinaryTaskElement {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let disk_element = MultiBinaryTaskElementDisk::deserialize(deserializer)?;

        let non_disk_element = MultiBinaryTaskElement::from(&disk_element);

        Ok(non_disk_element)
    }
}

impl MultiBinaryTaskElement {
    /// Creates a new element with the given number of subtasks
    fn with_empty_subtasks(subtask_count: usize) -> Self {
        Self {
            subtask_completion: vec![false; subtask_count],
            completion_override: false,
            text: UpgradedContent::default(),
        }
    }

    /// Set the completion status of the subtask at the given index
    pub fn set_subtask_completion(&mut self, completion_index: usize, completed: bool) {
        self.subtask_completion[completion_index] = completed;
    }

    /// Returns if the task as a whole is completed. If all subtasks are complete this returns true. If the completion
    /// has been manually overriden, this will return true, even if not all subtasks have been completed
    pub fn is_completed(&self) -> bool {
        if self.completion_override {
            return true;
        }

        self.subtask_completion
            .iter()
            .all(|&subtask_completed| subtask_completed)
    }

    /// Performs the action on the underlying UpgradedContent
    pub fn text_perform(&mut self, content_action: ContentAction) {
        self.text.perform(content_action);
    }
}

#[derive(Debug, Serialize, Deserialize)]
/// Contains the common and individual element entries in a MultiBinary task
pub struct MultiBinaryTask {
    subtasks: Vec<String>,
    elements: BTreeMap<NaiveDate, MultiBinaryTaskElement>,
}

impl MultiBinaryTask {
    /// Creates a new MultiBinaryTask with the given set of subtasks
    pub fn new(subtask_names: Vec<String>) -> Self {
        Self {
            subtasks: subtask_names,
            elements: BTreeMap::new(),
        }
    }

    /// Adds an empty element with the given date to the task elements if it does not exist
    pub fn add_empty_element(&mut self, active_date: NaiveDate) {
        let empty_element = MultiBinaryTaskElement::with_empty_subtasks(self.subtasks.len());

        self.elements.entry(active_date).or_insert(empty_element);
    }

    /// Returns mutable access to the task if it exists
    pub fn get_element_mut(
        &mut self,
        active_date: NaiveDate,
    ) -> Option<&mut MultiBinaryTaskElement> {
        self.elements.get_mut(&active_date)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Display, Serialize, Deserialize)]
/// The types of templates that can be created
pub enum TemplateTaskType {
    Standard,
    MultiBinary,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
/// the Frequency represents the schedule of how often the templates trigger
pub enum Frequency {
    Daily,
    Weekly([bool; 7]),
    Monthly([bool; 31]),
    Dated(MonthDay),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
/// a Frequency without any information about the schedule
pub enum FrequencyType {
    Daily,
    Weekly,
    Monthly,
    Dated,
}

impl Frequency {
    /// returns if the frequency would be scheduled to be active on the given date
    pub fn is_active(&self, active_date: NaiveDate) -> bool {
        match self {
            Frequency::Daily => {
                return true;
            }
            Frequency::Weekly(daymap) => {
                let current_day = active_date.weekday();

                if Self::weekly_is(current_day, daymap, Weekday::Sun) {
                    return true;
                }
            }
            Frequency::Monthly(daymap) => {
                let day_of_month = active_date.day0() as usize;

                if daymap[day_of_month] {
                    return true;
                }
            }
            Frequency::Dated(month_day) => {
                if active_date.month() == month_day.month().number_from_month()
                    && active_date.day() == month_day.day()
                {
                    return true;
                }
            }
        }

        false
    }

    /// checks if the given weekday would be active based on the daymap and the weekday defined as daymap[0]
    fn weekly_is(current_day: Weekday, daymap: &[bool; 7], week_start_day: Weekday) -> bool {
        let mut day_index = 0;

        let mut iterative_day = week_start_day;

        while iterative_day != current_day {
            iterative_day = iterative_day.succ();
            day_index += 1;
        }

        daymap[day_index]
    }
}

#[derive(Debug, Clone, PartialEq)]
/// types of messages that all TemplateTasks are able to create
pub enum CommonMessage {
    ExpandToggled,
    ExpandOptions,
    EndTask,
    DeleteTemplate,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum TemplateData {
    Standard(StandardTask),
    MultiBinary(MultiBinaryTask),
}

impl TemplateData {
    /// Conversion to TemplateTaskTypes
    pub fn task_type(&self) -> TemplateTaskType {
        match self {
            TemplateData::Standard(_) => TemplateTaskType::Standard,
            TemplateData::MultiBinary(_) => TemplateTaskType::MultiBinary,
        }
    }
}

#[derive(Debug, Serialize, Deserialize)]
/// Data that is used by all TemplateTasks
pub struct TemplateTask {
    name: String,
    creation_date: NaiveDate,
    ended_date: Option<NaiveDate>,
    frequency: Frequency,
    expanded: bool,
    options_expanded: bool,
    template_data: TemplateData,
}

impl TemplateTask {
    /// Creates new TemplateTask instance with the given values
    pub fn new(
        name: String,
        creation_date: NaiveDate,
        frequency: Frequency,
        template_data: TemplateData,
    ) -> Self {
        Self {
            name,
            creation_date,
            ended_date: None,
            frequency,
            expanded: false,
            options_expanded: false,
            template_data,
        }
    }

    /// Returns mutable access to the template data
    pub fn get_template_mut(&mut self) -> &mut TemplateData {
        &mut self.template_data
    }

    /// If the TemplateTask does not have an entry for the given day and it should based on its Frequency, a blank
    /// element is inserted into the elements
    pub fn generate_template_entry(&mut self, active_date: NaiveDate) {
        if self.frequency.is_active(active_date) {
            match &mut self.template_data {
                TemplateData::Standard(standard_task) => {
                    standard_task.add_empty_element(active_date);
                }
                TemplateData::MultiBinary(multi_binary_task) => {
                    multi_binary_task.add_empty_element(active_date);
                }
            }
        }
    }
}

#[derive(Debug, Clone)]
/// Messages that TemplateTasks can generate, represents some action to perform
pub enum TemplateMessage {
    Common(CommonMessage),
    Standard(StandardMessage),
    MultiBinary(MultiBinaryMessage),
}

#[derive(Debug, Clone)]
/// The actual TemplateTask message. The TaskId is which TemplateTask the message should be performed on
pub struct TemplateTaskMessage {
    pub(crate) message: TemplateMessage,
    pub(crate) task_id: TaskId,
}

#[derive(Debug, Default, Serialize, Deserialize)]
/// Collection of all the loaded templates
pub struct TemplateTasks {
    tasks: BTreeMap<TaskId, TemplateTask>,
}

impl<'a> TemplateTasks {
    /// Writes all template tasks to disk, into the template_tasks directory defined in the preferences
    pub fn save_templates(&self) {
        let mut template_path = preferences().paths.template_tasks_dir();
        template_path.push("templates.json");

        let template_json =
            serde_json::to_string_pretty(self).expect("couldn't serialize disk templates");

        fs::write(template_path, template_json).expect("couldn't save template json");
    }

    /// Loads all template tasks from disk, from the template_tasks directory defined in the preferences. If the
    /// templates file cannot be read, it returns an empty TemplateTasks
    pub fn load_templates() -> Self {
        let mut template_path = preferences().paths.template_tasks_dir();
        template_path.push("templates.json");

        if let Ok(template_string) = fs::read_to_string(template_path)
            && let Ok(template_disk) = serde_json::from_str::<TemplateTasks>(&template_string)
        {
            if let Some(max_id) = template_disk.tasks.keys().max() {
                TaskId::set_if_greater(max_id.as_u32() + 1);
            }

            template_disk
        } else {
            Self::default()
        }
    }

    /// Inserts a new template task into the structure
    pub fn create_task(&mut self, mut template: TemplateTask) {
        let task_id = TaskId::new_unique_id();

        let task_date = template.creation_date;

        template.generate_template_entry(task_date);

        self.tasks.insert(task_id, template);
    }

    /// Generate any missing entries for tasks scheduled on the given date
    pub fn generate_template_entries(&mut self, active_date: NaiveDate) {
        let active_templates = self.get_active_template_ids(active_date);

        for task_id in active_templates {
            if let Some(task) = self.tasks.get_mut(&task_id) {
                task.generate_template_entry(active_date);
            }
        }
    }

    /// Returns the task at the given TaskId, if it exists
    pub fn get_task(&self, task_id: TaskId) -> Option<&TemplateTask> {
        self.tasks.get(&task_id)
    }

    /// Returns mutable access the task at the given TaskId, if it exists
    pub fn get_task_mut(&mut self, task_id: TaskId) -> Option<&mut TemplateTask> {
        self.tasks.get_mut(&task_id)
    }

    /// Returns true if given name and task type are present in the same TemplateTask
    pub fn task_exists(&self, task_name: &str, task_type: TemplateTaskType) -> bool {
        for task in self.tasks.values() {
            if task.name == task_name && task.template_data.task_type() == task_type {
                return true;
            }
        }

        false
    }

    /// Performs the action specified by the message on the TemplateTask on the given date
    pub fn update(&mut self, active_date: NaiveDate, message: TemplateTaskMessage) {
        match message.message {
            TemplateMessage::Common(common_message) => {
                if let Some(template) = self.tasks.get_mut(&message.task_id) {
                    match common_message {
                        CommonMessage::ExpandToggled => {
                            template.expanded = !template.expanded;
                        }
                        CommonMessage::ExpandOptions => {
                            template.options_expanded = !template.options_expanded
                        }
                        CommonMessage::EndTask => {
                            template.ended_date = Some(active_date);
                        }
                        CommonMessage::DeleteTemplate => {
                            self.tasks.remove(&message.task_id);
                        }
                    }
                }
            }
            TemplateMessage::Standard(standard_message) => {
                if let Some(task) = self.tasks.get_mut(&message.task_id)
                    && let TemplateData::Standard(standard_task) = &mut task.template_data
                    && let Some(task_element) = standard_task.elements.get_mut(&active_date)
                {
                    match standard_message {
                        StandardMessage::CheckedBox(checked) => {
                            task_element.set_completion(checked);
                        }
                        StandardMessage::TextEdit(content_action) => {
                            task_element.text.perform(content_action);
                        }
                    }
                }
            }
            TemplateMessage::MultiBinary(multi_binary_message) => {
                if let Some(task) = self.tasks.get_mut(&message.task_id)
                    && let TemplateData::MultiBinary(multi_binary_task) = &mut task.template_data
                    && let Some(task_element) = multi_binary_task.elements.get_mut(&active_date)
                {
                    match multi_binary_message {
                        MultiBinaryMessage::CheckedNth((index, checked)) => {
                            task_element.set_subtask_completion(index, checked);
                        }
                        MultiBinaryMessage::CheckedOverride(checked) => {
                            task_element.completion_override = checked;
                        }
                        MultiBinaryMessage::TextEdit(content_action) => {
                            task_element.text.perform(content_action);
                        }
                    }
                }
            }
        }
    }

    /// Returns a list of all the templates that are active on a given date
    pub fn get_active_template_ids(&self, active_date: NaiveDate) -> Vec<TaskId> {
        self.tasks
            .iter()
            .filter(|(_id, data)| {
                let after_end_date = data
                    .ended_date
                    .is_some_and(|ended_date| active_date > ended_date);

                data.frequency.is_active(active_date)
                    && active_date >= data.creation_date
                    && !after_end_date
            })
            .map(|(id, _data)| *id)
            .collect::<Vec<TaskId>>()
    }

    /// Graphical layout of a task that is minimized
    fn minimized_task<T: 'a>(
        checkbox: Element<'a, T>,
        name: Element<'a, T>,
        expand_button: Element<'a, T>,
        options_button: Element<'a, T>,
    ) -> Element<'a, T> {
        row![
            checkbox,
            Space::new().width(5),
            name,
            Space::new().width(Fill),
            expand_button,
            Space::new().width(5),
            options_button,
        ]
        .into()
    }

    /// Full TemplateTask graphical element
    pub fn build_template(
        &'a self,
        task_id: TaskId,
        active_date: NaiveDate,
    ) -> Element<'a, TemplateTaskMessage> {
        if let Some(task_data) = self.get_task(task_id) {
            let name = Text::new(task_data.name.clone());

            let expand_button_text = if task_data.expanded { "\\/" } else { "<" };

            let expand_button =
                button(Text::new(expand_button_text)).on_press(TemplateTaskMessage {
                    message: TemplateMessage::Common(CommonMessage::ExpandToggled),
                    task_id,
                });

            let options_button = button("...").on_press(TemplateTaskMessage {
                message: TemplateMessage::Common(CommonMessage::ExpandOptions),
                task_id,
            });

            let task_ui = match &task_data.template_data {
                TemplateData::Standard(standard_task) => {
                    if let Some(task_element) = standard_task.elements.get(&active_date) {
                        let checkbox = checkbox(task_element.completed).on_toggle(move |ticked| {
                            TemplateTaskMessage {
                                message: TemplateMessage::Standard(StandardMessage::CheckedBox(
                                    ticked,
                                )),
                                task_id,
                            }
                        });

                        let minimized_task = Self::minimized_task(
                            checkbox.into(),
                            name.into(),
                            expand_button.into(),
                            options_button.into(),
                        );

                        let text = widget::text_editor(task_element.text.raw_content()).on_action(
                            move |action| TemplateTaskMessage {
                                message: TemplateMessage::Standard(StandardMessage::TextEdit(
                                    ContentAction::Standard(action),
                                )),
                                task_id,
                            },
                        );

                        if !task_data.expanded {
                            minimized_task
                        } else {
                            column![minimized_task, text].into()
                        }
                    } else {
                        column![].into()
                    }
                }
                TemplateData::MultiBinary(multi_binary_task) => {
                    if let Some(task_element) = multi_binary_task.elements.get(&active_date) {
                        let completed_checkbox =
                            checkbox(task_element.is_completed()).on_toggle(move |ticked| {
                                TemplateTaskMessage {
                                    message: TemplateMessage::MultiBinary(
                                        MultiBinaryMessage::CheckedOverride(ticked),
                                    ),
                                    task_id,
                                }
                            });

                        let minimized_task = Self::minimized_task(
                            completed_checkbox.into(),
                            name.into(),
                            expand_button.into(),
                            options_button.into(),
                        );

                        let mut subtask_checkboxes = column![];

                        for (i, completion) in task_element.subtask_completion.iter().enumerate() {
                            let checkbox = checkbox(*completion).on_toggle(move |ticked| {
                                TemplateTaskMessage {
                                    message: TemplateMessage::MultiBinary(
                                        MultiBinaryMessage::CheckedNth((i, ticked)),
                                    ),
                                    task_id,
                                }
                            });

                            let subtask_name = &multi_binary_task.subtasks[i];

                            let name_text = Text::new(subtask_name);

                            subtask_checkboxes = subtask_checkboxes.push(row![
                                Space::new().width(15),
                                checkbox,
                                Space::new().width(5),
                                name_text
                            ]);
                        }

                        let text = widget::text_editor(task_element.text.raw_content()).on_action(
                            move |action| TemplateTaskMessage {
                                message: TemplateMessage::MultiBinary(
                                    MultiBinaryMessage::TextEdit(ContentAction::Standard(action)),
                                ),
                                task_id,
                            },
                        );

                        if !task_data.expanded {
                            minimized_task
                        } else {
                            column![minimized_task, subtask_checkboxes, text].into()
                        }
                    } else {
                        column![].into()
                    }
                }
            };

            if task_data.options_expanded {
                let end_task_button = button("End Task").on_press(TemplateTaskMessage {
                    message: TemplateMessage::Common(CommonMessage::EndTask),
                    task_id,
                });

                let delete_button = button("Delete Task").on_press(TemplateTaskMessage {
                    message: TemplateMessage::Common(CommonMessage::DeleteTemplate),
                    task_id,
                });

                let options_menu = column![end_task_button, delete_button];

                column![task_ui, options_menu].into()
            } else {
                task_ui
            }
        } else {
            column![].into()
        }
    }
}
